### PR TITLE
[Chaos] - Add trigger to run experiment periodically

### PR DESCRIPTION
**Pull request by see-quick**

### CODE REVIEW

**Comment by kornys** [comment]
@see-quick please add it to same file like we do for every triggered pipeline

**Comment by see-quick** [comment]
> @see-quick please add it to the same file as we do for every triggered pipeline

Okay, but I want to have at least CronJob separated. Because in this folder I would add more CronJobs where I would change 
```
-d '{"chaosCommand": "--pod-chaos anubis-kafka-kill-random-pod --enable-probes"}'  
```
part. So I could aggregate `EventListener`, `TriggerBinding` and `TriggerTemplate`.

**Comment by kornys** [comment]
@see-quick trigger template etc should be in the same file as pipeline, cron job okey leave it as is in different file.

**Comment by see-quick** [comment]
> @see-quick trigger template etc should be in the same file as pipeline, cron job okey leave it as is in different file.

done

**Review by kornys — APPROVED** [review]

**Pull request merged**
